### ISSUE TITLE
Cannot build html reports - jpg not supported.

### ISSUE THREAD

**Issue by masasin** [MartinPyka/financial_life#12]
Traceback:
```
Traceback (most recent call last):
  File "simple.py", line 135, in <module>
    example2()
  File "simple.py", line 81, in example2
    html.report(simulation, style="standard", output_dir = result_folder)
  File "/home/masasin/.virtualenvs/financial_life/lib/python3.6/site-packages/financial_life/reports/html.py", line 34, in report
    render_module.render(simulation, output_dir)
  File "/home/masasin/.virtualenvs/financial_life/lib/python3.6/site-packages/financial_life/reports/../templates/html/standard/render.py", line 35, in render
    img_data = plt.summary_img(*simulation.reports('yearly'), target = img_folder)
  File "/home/masasin/.virtualenvs/financial_life/lib/python3.6/site-packages/financial_life/financing/plotting.py", line 74, in summary_img
    fig.savefig(target + prefix + 'wealth.jpg', dpi = dpi)
  File "/home/masasin/.virtualenvs/financial_life/lib/python3.6/site-packages/matplotlib/figure.py", line 1573, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/home/masasin/.virtualenvs/financial_life/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2153, in print_figure
    canvas = self._get_output_canvas(format)
  File "/home/masasin/.virtualenvs/financial_life/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2093, in _get_output_canvas
    '%s.' % (format, ', '.join(formats)))
ValueError: Format "jpg" is not supported.
Supported formats: eps, pdf, pgf, png, ps, raw, rgba, svg, svgz.     
```

**Comment by MartinPyka** [comment]
based on a report here https://stackoverflow.com/questions/8827016/matplotlib-savefig-in-jpeg-format installing the pillow python package should resolve it. But I changed the output format to png to avoid this dependency: https://github.com/MartinPyka/financial_life/commit/a92553b09c713bea8b81dff964e150d0c46c696d

again, thanks for your helpful contribution
